# Generated by Django 2.0.2 on 2018-05-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20180512_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='devis_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='logo_url',
            field=models.URLField(null=True),
        ),
    ]
