# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-03 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_etudiant_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='user_id',
        ),
    ]
