# Generated by Django 2.0.2 on 2018-05-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_auto_20180519_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendrier',
            name='duration',
        ),
        migrations.AddField(
            model_name='calendrier',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='calendrier',
            name='title',
            field=models.CharField(default='Date', max_length=64),
        ),
    ]
