# Generated by Django 2.0.2 on 2018-05-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0007_auto_20180519_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendrier',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
