# Generated by Django 2.0.4 on 2018-04-22 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('type_mission', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('logo_url', models.URLField()),
                ('devis_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Techno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='cv_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='mission.Prestataire'),
        ),
        migrations.AddField(
            model_name='mission',
            name='commercial_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Prestataire'),
        ),
        migrations.AddField(
            model_name='mission',
            name='techno',
            field=models.ManyToManyField(to='mission.Techno'),
        ),
    ]
