# Generated by Django 2.0.4 on 2018-04-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20180422_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendrier',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='commercial_id',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='techno',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Prestataire',
        ),
        migrations.DeleteModel(
            name='Techno',
        ),
    ]
