# Generated by Django 2.0.4 on 2018-04-23 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission', '0003_auto_20180423_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_hour', models.DateTimeField()),
                ('duration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('cv_url', models.URLField(null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('type_mission', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publication_date', models.DateTimeField(null=True)),
                ('client_name', models.CharField(max_length=64)),
                ('logo_url', models.URLField()),
                ('devis_url', models.URLField()),
                ('commercial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Techno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='techno',
            field=models.ManyToManyField(to='mission.Techno'),
        ),
    ]
