# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='num_presta',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mission',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
