# Generated by Django 2.0.2 on 2018-05-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_auto_20180512_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendrier',
            old_name='begin_hour',
            new_name='date',
        ),
    ]
