# Generated by Django 2.0.2 on 2018-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_auto_20180519_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendrier',
            name='date',
            field=models.DateField(),
        ),
    ]
